version: '3.8'

services:
  redcap-dashboard:
    build: .
    ports:
      - "80:80"
    environment:
      - VITE_REDCAP_API_URL=${VITE_REDCAP_API_URL}
      - VITE_REDCAP_API_TOKEN=${VITE_REDCAP_API_TOKEN}
    restart: unless-stopped 