name: Deploy to DigitalOcean

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Clean install dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install --legacy-peer-deps
          
      - name: Run tests
        run: |
          npm install @rollup/rollup-linux-x64-gnu --save-dev
          npm test
        
      - name: Build
        run: npm run build
        env:
          VITE_REDCAP_API_URL: ${{ secrets.VITE_REDCAP_API_URL }}
          VITE_REDCAP_API_TOKEN: ${{ secrets.VITE_REDCAP_API_TOKEN }}

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            cd ${{ secrets.DROPLET_PATH }}
            git pull origin main
            echo "VITE_REDCAP_API_URL=${{ secrets.VITE_REDCAP_API_URL }}" > .env
            echo "VITE_REDCAP_API_TOKEN=${{ secrets.VITE_REDCAP_API_TOKEN }}" >> .env
            docker compose build --no-cache
            docker compose up -d 